package com.company.modernizer.report;

import com.company.modernizer.model.*;
import org.springframework.stereotype.Component;

import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Component
public class ClaudeMigrationPlanRenderer {

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("d MMM yyyy 'at' HH:mm:ss 'UTC'")
                    .withZone(ZoneOffset.UTC);

    public String render(ModernizationReport report) {
        StringBuilder md = new StringBuilder(16_384);

        ProjectInfo project = report.project();

        String projectName = project == null
                ? "Unknown project"
                : project.name();

        md.append("# Claude Migration Plan\n\n");

        md.append("> This file was generated by the AI Java Modernization Agent. ")
                .append("It is intended to be used as an execution plan by Claude Code ")
                .append("or another coding agent.\n\n");

        md.append("---\n\n");

        // -----------------------------------------------------------------
        // 1. Project Overview
        // -----------------------------------------------------------------

        md.append("# 1. Project Overview\n\n");

        appendBullet(md, "Project", projectName);

        if (project != null) {
            appendBullet(md, "Build Tool", String.valueOf(project.buildTool()));

            if (project.detectedJavaVersion() != null) {
                appendBullet(md, "Current Java Version",
                        project.detectedJavaVersion());
            }

            if (!project.modules().isEmpty()) {
                appendBullet(md, "Modules",
                        String.join(", ", project.modules()));
            }
        }

        md.append("\n");

        // -----------------------------------------------------------------
        // 2. Migration Objective
        // -----------------------------------------------------------------

        md.append("# 2. Migration Objective\n\n");

        md.append("""
                The objective is to modernize this application while preserving
                existing business behavior and externally visible functionality.

                The migration must be performed incrementally. After each major
                migration phase, build and test the application before continuing.

                **Do not remove business functionality simply to make the build pass.**

                """);

        // -----------------------------------------------------------------
        // 3. Project Metrics
        // -----------------------------------------------------------------

        if (project != null && project.metrics() != null) {
            ProjectMetrics metrics = project.metrics();

            md.append("# 3. Project Metrics\n\n");

            appendBullet(md, "Java source files",
                    String.valueOf(metrics.javaFiles()));

            appendBullet(md, "Test classes",
                    String.valueOf(metrics.testFiles()));

            appendBullet(md, "Test/source ratio",
                    String.format("%.2f", metrics.testToSourceRatio()));

            appendBullet(md, "Lines of code",
                    String.valueOf(metrics.linesOfCode()));

            appendBullet(md, "XML configuration files",
                    String.valueOf(metrics.xmlConfigFiles()));

            appendBullet(md, "WSDL contracts",
                    String.valueOf(metrics.wsdlFiles()));

            appendBullet(md, "JSP views",
                    String.valueOf(metrics.jspFiles()));

            appendBullet(md, "Declared dependencies",
                    String.valueOf(metrics.declaredDependencies()));

            md.append("\n");
        }

        // -----------------------------------------------------------------
        // 4. Detected Frameworks
        // -----------------------------------------------------------------

        if (project != null && !project.detectedFrameworks().isEmpty()) {

            md.append("# 4. Detected Frameworks\n\n");

            for (FrameworkRef framework : project.detectedFrameworks()) {
                md.append("- **")
                        .append(framework.name())
                        .append("**");

                if (framework.version() != null
                        && !framework.version().isBlank()) {
                    md.append(" — ")
                            .append(framework.version());
                }

                md.append("\n");
            }

            md.append("\n");
        }

        // -----------------------------------------------------------------
        // 5. Migration Strategy
        // -----------------------------------------------------------------

        md.append("# 5. Migration Strategy\n\n");

        md.append("""
                Execute the migration in the following order:

                1. Establish the baseline.
                2. Update the build system if required.
                3. Upgrade the Java runtime/compiler configuration.
                4. Upgrade incompatible dependencies.
                5. Remediate source-code compatibility issues.
                6. Address framework/API migration issues.
                7. Address security-related findings.
                8. Execute the existing test suite.
                9. Fix regressions.
                10. Perform final validation.

                Do not perform all changes in one step.

                """);

        // -----------------------------------------------------------------
        // 6. Baseline
        // -----------------------------------------------------------------

        md.append("# 6. Baseline Before Migration\n\n");

        md.append("""
                Before modifying the source code:

                - Record the current Java version.
                - Record the current build command.
                - Execute the existing build.
                - Execute the existing test suite.
                - Record existing test failures separately from migration failures.
                - Preserve the baseline results for comparison after migration.

                Recommended baseline evidence:

                ```text
                Java version:
                Build command:
                Build result:
                Test command:
                Test result:
                Existing failures:
                ```

                """);

        // -----------------------------------------------------------------
        // 7. Findings
        // -----------------------------------------------------------------

        md.append("# 7. Migration Findings\n\n");

        if (report.findings().isEmpty()) {
            md.append("No findings were generated by the available analyzers.\n\n");
        } else {
            int index = 1;

            for (Finding finding : report.findingsBySeverity()) {
                renderFinding(md, finding, index++);
            }
        }

        // -----------------------------------------------------------------
        // 8. Dependency Migration
        // -----------------------------------------------------------------

        md.append("# 8. Dependency Migration\n\n");

        md.append("""
                Review every declared dependency for compatibility with the
                target Java version and target framework versions.

                For each dependency:

                - Identify the currently declared version.
                - Determine whether it supports the target Java version.
                - Upgrade only when required or justified by the migration.
                - Check transitive dependency changes.
                - Check for breaking API changes.
                - Rebuild after dependency changes.
                - Run tests after dependency changes.

                Do not blindly upgrade all dependencies to their latest versions.

                """);

        // -----------------------------------------------------------------
        // 9. Execution Rules
        // -----------------------------------------------------------------

        md.append("# 9. Claude Execution Rules\n\n");

        md.append("""
                ## 9.1 Preserve Business Logic

                Do not rewrite business logic unless a finding explicitly
                identifies a compatibility issue requiring the change.

                ## 9.2 Make Small Changes

                Apply migration changes in small logical groups.

                ## 9.3 Build After Changes

                After each major phase:

                ```text
                build
                ↓
                compile
                ↓
                test
                ↓
                inspect failures
                ↓
                continue
                ```

                ## 9.4 Do Not Hide Failures

                Never comment out tests, remove code, suppress compiler errors,
                or downgrade the target Java version merely to obtain a
                successful build.

                ## 9.5 Document Changes

                Maintain a migration log containing:

                - file changed
                - reason
                - old implementation
                - new implementation
                - validation performed

                """);

        // -----------------------------------------------------------------
        // 10. Validation
        // -----------------------------------------------------------------

        md.append("# 10. Final Validation\n\n");

        md.append("""
                The migration is complete only when:

                - [ ] Target Java version is configured.
                - [ ] Build completes successfully.
                - [ ] Required dependencies are compatible.
                - [ ] Existing tests execute successfully.
                - [ ] Migration-related regressions are resolved.
                - [ ] No critical findings remain unresolved.
                - [ ] Security findings have been reviewed.
                - [ ] Public API behavior has been preserved where required.
                - [ ] Configuration changes are documented.
                - [ ] Migration changes are documented.

                """);

        // -----------------------------------------------------------------
        // 11. Migration Completion Report
        // -----------------------------------------------------------------

        md.append("# 11. Migration Completion Report\n\n");

        md.append("""
                At the end of the migration, produce the following summary:

                ```text
                Migration status:
                Source Java version:
                Target Java version:

                Build:
                Tests:

                Findings resolved:
                Findings remaining:

                Files modified:

                Breaking changes:

                Additional manual validation required:
                ```

                """);

        // -----------------------------------------------------------------
        // 12. Report Metadata
        // -----------------------------------------------------------------

        md.append("# 12. Assessment Metadata\n\n");

        if (report.meta() != null) {
            appendBullet(md, "Analyzer version",
                    report.meta().analyzerVersion());

            appendBullet(md, "AI assessment",
                    report.meta().aiAssessmentEnabled()
                            ? "enabled"
                            : "disabled");

            if (report.meta().scan() != null) {
                appendBullet(md, "Files scanned",
                        String.valueOf(report.meta().scan().filesScanned()));

                appendBullet(md, "Scan duration",
                        report.meta().scan().durationMs() + " ms");
            }
        }

        if (report.generatedAt() != null) {
            appendBullet(md, "Generated",
                    TIMESTAMP.format(report.generatedAt()));
        }

        md.append("\n");

        md.append("---\n\n");
        md.append("Generated by **AI Java Modernization Agent**.\n");

        return md.toString();
    }

    private void renderFinding(
            StringBuilder md,
            Finding finding,
            int number) {

        md.append("## 7.")
                .append(number)
                .append(" ")
                .append(safe(finding.title()))
                .append("\n\n");

        md.append("| Property | Value |\n");
        md.append("|---|---|\n");

        appendTableRow(md, "Finding ID", finding.id());
        appendTableRow(md, "Severity", finding.severity());
        appendTableRow(md, "Category",
                finding.category() == null
                        ? null
                        : finding.category().displayName());
        appendTableRow(md, "Effort", finding.effort());
        appendTableRow(md, "Risk", finding.risk());
        appendTableRow(md, "Confidence", finding.confidence());
        appendTableRow(md, "Source", finding.source());

        md.append("\n");

        if (finding.currentState() != null
                || finding.targetState() != null) {

            md.append("### Current → Target\n\n");

            md.append("**Current:** ")
                    .append(safe(finding.currentState()))
                    .append("\n\n");

            md.append("**Target:** ")
                    .append(safe(finding.targetState()))
                    .append("\n\n");
        }

        if (finding.impact() != null) {
            md.append("### Why This Matters\n\n")
                    .append(finding.impact())
                    .append("\n\n");
        }

        if (finding.recommendation() != null) {
            md.append("### Required Change\n\n")
                    .append(finding.recommendation())
                    .append("\n\n");
        }

        if (!finding.blockedBy().isEmpty()) {
            md.append("### Blocked By\n\n");

            for (String dependency : finding.blockedBy()) {
                md.append("- `")
                        .append(dependency)
                        .append("`\n");
            }

            md.append("\n");
        }

        if (!finding.blocks().isEmpty()) {
            md.append("### Blocks\n\n");

            for (String dependency : finding.blocks()) {
                md.append("- `")
                        .append(dependency)
                        .append("`\n");
            }

            md.append("\n");
        }

        if (!finding.evidence().isEmpty()) {
            md.append("### Evidence\n\n");

            for (Evidence evidence : finding.evidence()) {
                md.append("- **Location:** `")
                        .append(evidence.location())
                        .append("`\n");

                if (evidence.snippet() != null
                        && !evidence.snippet().isBlank()) {

                    md.append("\n```text\n")
                            .append(evidence.snippet())
                            .append("\n```\n");
                }

                md.append("\n");
            }
        }

        if (!finding.references().isEmpty()) {
            md.append("### References\n\n");

            for (String reference : finding.references()) {
                md.append("- ")
                        .append(reference)
                        .append("\n");
            }

            md.append("\n");
        }

        md.append("### Claude Action Checklist\n\n");

        md.append("- [ ] Inspect the affected files.\n");
        md.append("- [ ] Confirm the finding against the source code.\n");
        md.append("- [ ] Apply the recommended migration.\n");
        md.append("- [ ] Build the affected module.\n");
        md.append("- [ ] Execute relevant tests.\n");
        md.append("- [ ] Review the resulting diff.\n");
        md.append("- [ ] Document the change.\n\n");
    }

    private static void appendBullet(
            StringBuilder md,
            String label,
            Object value) {

        md.append("- **")
                .append(label)
                .append(":** ")
                .append(safe(String.valueOf(value)))
                .append("\n");
    }

    private static void appendTableRow(
            StringBuilder md,
            String property,
            Object value) {

        md.append("| ")
                .append(property)
                .append(" | ")
                .append(safe(String.valueOf(value)))
                .append(" |\n");
    }

    private static String safe(String value) {
        return value == null || value.isBlank()
                ? "Not specified"
                : value;
    }
}